[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[functions]
  node_bundler = "esbuild"

[[functions]]
  name = "analyze-concepts"
  timeout = 120

[[functions]]
  name = "analyze-gaps"
  timeout = 90

[functions."*"]
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 3000