[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  timeout = 60 

[functions."api/analyze-gaps"]
  timeout = 90

[functions."api/analyze-concepts"]
  timeout = 120

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 3000